/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "dbus-java-parent"
include(":dbus-java-osgi")
include(":dbus-java-examples")
include(":dbus-java-utils")
include(":dbus-java-transport-native-unixsocket")
include(":dbus-java-core")
include(":dbus-java-bom")
include(":dbus-java-transport-junixsocket")
include(":dbus-java-tests")
include(":dbus-java-transport-jnr-unixsocket")
include(":dbus-java-transport-tcp")
