/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.github.hypfvieh.java-conventions")
}

dependencies {
    api(project(":dbus-java-core"))
    api("com.github.hypfvieh:java-utils:1.2.0")
    runtimeOnly(project(":dbus-java-transport-jnr-unixsocket"))
    runtimeOnly(project(":dbus-java-transport-tcp"))
    runtimeOnly("ch.qos.logback:logback-core:1.4.9")
    runtimeOnly("ch.qos.logback:logback-classic:1.4.9")
}

description = "dbus-java-examples"

java {
    withJavadocJar()
}
