/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.github.hypfvieh.java-conventions")
}

dependencies {
    api(project(":dbus-java-core"))
    testImplementation(project(":dbus-java-transport-tcp"))
    testImplementation(project(":dbus-java-transport-jnr-unixsocket"))
    testImplementation(project(":dbus-java-transport-junixsocket"))
    testImplementation("ch.qos.logback:logback-core:1.4.9")
    testImplementation("ch.qos.logback:logback-classic:1.4.9")
    testImplementation(project(":dbus-java-transport-native-unixsocket"))
}

description = "dbus-java-tests"

java {
    withJavadocJar()
}
