/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.github.hypfvieh.java-conventions")
}

dependencies {
    api("org.eclipse.jdt:org.eclipse.jdt.annotation:2.2.600")
    api("com.github.jnr:jnr-unixsocket:0.38.20")
    api("com.diffplug.osgi:com.diffplug.osgi.extension.sun.misc:0.0.0")
}

description = "dbus-java-osgi"

java {
    withJavadocJar()
}
