package org.freedesktop.dbus.transport.tcp;

import org.freedesktop.dbus.connections.BusAddress;
import org.freedesktop.dbus.connections.SASL;
import org.freedesktop.dbus.connections.config.TransportConfig;
import org.freedesktop.dbus.connections.transports.AbstractTransport;
import org.freedesktop.dbus.exceptions.AuthenticationException;

import java.io.IOException;
import java.net.Inet4Address;
import java.net.Inet6Address;
import java.net.InetAddress;
import java.net.InetSocketAddress;
import java.nio.ByteBuffer;
import java.nio.channels.ServerSocketChannel;
import java.nio.channels.SocketChannel;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.attribute.PosixFilePermission;
import java.security.SecureRandom;
import java.util.Arrays;
import java.util.Locale;
import java.util.Set;

/**
 * Transport type representing a transport connection to TCP.
 *
 * @author hypfvieh
 * @since v3.2.0 - 2019-02-08
 */
public class TcpTransport extends AbstractTransport {

    /** Length of the nonce exchanged for the {@code nonce-tcp} transport (D-Bus specification). */
    private static final int          NONCE_LENGTH  = 16;

    /** Shared secure random source used to generate the server nonce (nonce-tcp). */
    private static final SecureRandom SECURE_RANDOM = new SecureRandom();

    private final int           timeout;

    private SocketChannel       socket;
    private ServerSocketChannel serverSocket;

    /** The nonce generated by the server (nonce-tcp only). */
    private byte[]              serverNonce;

    TcpTransport(BusAddress _address, int _timeout, TransportConfig _config) {
        super(_address, _config);
        timeout = _timeout;
        getSaslConfig().setAuthMode(SASL.AUTH_SHA);
    }

    @Override
    protected boolean hasFileDescriptorSupport() {
        return false; // file descriptor passing not possible on TCP connections
    }

    @Override
    public TcpBusAddress getAddress() {
        return (TcpBusAddress) super.getAddress();
    }

    @Override
    protected boolean isBound() {
        return serverSocket != null && serverSocket.isOpen();
    }

    /**
     * Listen for new connections using TCP.
     *
     * @throws IOException on error
     */
    @Override
    protected void bindImpl() throws IOException {
        if (!getAddress().isListeningSocket()) {
            throw new IOException("Cannot listen on client connections (use connectImpl() instead)");
        }

        if (!isBound()) {
            InetSocketAddress socketAddress = createBindAddress();
            serverSocket = ServerSocketChannel.open();
            serverSocket.configureBlocking(true);
            getLogger().debug("Binding to {} using local port {}", socketAddress.getAddress(),
                getAddress().getPort());

            serverSocket.bind(socketAddress);

            if (getAddress().isNonceTcp()) {
                writeNonceFile();
            }
        }
    }

    /**
     * Creates the socket address to bind the server socket to, honouring the optional {@code bind} and {@code family}
     * address parameters. When {@code bind} is missing, the advertised {@code host} is used; {@code bind=*} binds to all
     * interfaces.
     *
     * @return bind address
     * @throws IOException if the host/family cannot be resolved
     */
    private InetSocketAddress createBindAddress() throws IOException {
        TcpBusAddress address = getAddress();
        int port = address.getPort();
        String bindHost = address.hasBind() ? address.getBind() : address.getHost();

        if ("*".equals(bindHost)) {
            InetAddress wildcard = wildcardAddress(address.getFamily());
            return wildcard == null ? new InetSocketAddress(port) : new InetSocketAddress(wildcard, port);
        }

        return new InetSocketAddress(resolveWithFamily(bindHost, address.getFamily()), port);
    }

    @Override
    protected SocketChannel acceptImpl() throws IOException {
        socket = serverSocket.accept();
        if (getAddress().isNonceTcp()) {
            verifyClientNonce(socket);
        }
        return socket;
    }

    /**
     * Connect to DBus using TCP.
     *
     * @throws IOException on error
     */
    @Override
    public SocketChannel connectImpl() throws IOException {

        if (getAddress().isListeningSocket()) {
            throw new IOException("Connect connect to a listening socket (use listenImpl() instead)");
        }

        InetSocketAddress socketAddress = getAddress().hasFamily()
            ? new InetSocketAddress(resolveWithFamily(getAddress().getHost(), getAddress().getFamily()), getAddress().getPort())
            : new InetSocketAddress(getAddress().getHost(), getAddress().getPort());

        socket = SocketChannel.open();
        socket.configureBlocking(true);

        getLogger().trace("Setting timeout to {} on Socket", timeout);
        socket.socket().connect(socketAddress, timeout);
        getLogger().debug("Connected to {} using local port {} and remote port {}", getAddress().getHost(),
            getAddress().getPort(), socket.socket().getLocalPort());

        if (getAddress().isNonceTcp()) {
            // the nonce read from the noncefile must be sent before anything else (i.e. before SASL)
            sendClientNonce(socket);
        }

        return socket;
    }

    /**
     * Resolves the given host to an {@link InetAddress} of the requested address family.
     *
     * @param _host host name or literal IP
     * @param _family requested family ({@code ipv4}/{@code ipv6}) or null for no restriction
     *
     * @return matching address
     * @throws IOException if the family is unknown or no matching address exists
     */
    private static InetAddress resolveWithFamily(String _host, String _family) throws IOException {
        if (_family == null) {
            return InetAddress.getByName(_host);
        }

        Class<? extends InetAddress> wanted = familyClass(_family);
        for (InetAddress addr : InetAddress.getAllByName(_host)) {
            if (wanted.isInstance(addr)) {
                return addr;
            }
        }
        throw new IOException("No " + _family + " address found for host '" + _host + "'");
    }

    /**
     * Returns the wildcard ("any local") address for the given family, or null when no family is requested (in which
     * case the caller should bind to the family-agnostic wildcard).
     */
    private static InetAddress wildcardAddress(String _family) throws IOException {
        if (_family == null) {
            return null;
        }
        return switch (_family.toLowerCase(Locale.US)) {
            case "ipv4" -> InetAddress.getByName("0.0.0.0");
            case "ipv6" -> InetAddress.getByName("::");
            default -> throw new IOException("Unsupported address family '" + _family + "'");
        };
    }

    private static Class<? extends InetAddress> familyClass(String _family) throws IOException {
        return switch (_family.toLowerCase(Locale.US)) {
            case "ipv4" -> Inet4Address.class;
            case "ipv6" -> Inet6Address.class;
            default -> throw new IOException("Unsupported address family '" + _family + "'");
        };
    }

    /**
     * Generates a random nonce and writes it to the configured nonce file (server side).
     *
     * @throws IOException if no nonce file is configured or writing fails
     */
    private void writeNonceFile() throws IOException {
        String nonceFile = getAddress().getNonceFile();
        if (nonceFile == null) {
            throw new IOException("nonce-tcp listening address requires a 'noncefile' parameter");
        }

        serverNonce = new byte[NONCE_LENGTH];
        SECURE_RANDOM.nextBytes(serverNonce);

        Path path = Path.of(nonceFile);
        Files.write(path, serverNonce);
        // best effort: restrict the nonce file to the owner (ignored on non-POSIX file systems)
        try {
            Files.setPosixFilePermissions(path, Set.of(PosixFilePermission.OWNER_READ, PosixFilePermission.OWNER_WRITE));
        } catch (UnsupportedOperationException | IOException _ex) {
            getLogger().debug("Could not restrict permissions of nonce file {}", nonceFile, _ex);
        }
        getLogger().debug("Wrote nonce file {}", nonceFile);
    }

    /**
     * Reads the client nonce from the accepted connection and compares it to the server nonce.
     *
     * @param _channel accepted client channel
     * @throws IOException if the nonce does not match or cannot be read
     */
    private void verifyClientNonce(SocketChannel _channel) throws IOException {
        byte[] received = readFully(_channel, NONCE_LENGTH);
        if (serverNonce == null || !Arrays.equals(serverNonce, received)) {
            _channel.close();
            // AuthenticationException is handled by the accept loop: the offending connection is dropped
            // while the daemon keeps listening for other clients
            throw new AuthenticationException("Rejected connection: invalid nonce received");
        }
        getLogger().trace("Client provided a valid nonce");
    }

    /**
     * Reads the nonce from the configured nonce file and sends it on the given channel (client side).
     *
     * @param _channel connected channel
     * @throws IOException if the nonce file is missing/too short or writing fails
     */
    private void sendClientNonce(SocketChannel _channel) throws IOException {
        String nonceFile = getAddress().getNonceFile();
        if (nonceFile == null) {
            throw new IOException("nonce-tcp address requires a 'noncefile' parameter");
        }

        byte[] fileContent = Files.readAllBytes(Path.of(nonceFile));
        if (fileContent.length < NONCE_LENGTH) {
            throw new IOException("Nonce file " + nonceFile + " is too short (expected at least " + NONCE_LENGTH + " bytes)");
        }

        writeFully(_channel, Arrays.copyOf(fileContent, NONCE_LENGTH));
        getLogger().trace("Sent nonce from {}", nonceFile);
    }

    private static byte[] readFully(SocketChannel _channel, int _length) throws IOException {
        ByteBuffer buf = ByteBuffer.allocate(_length);
        while (buf.hasRemaining()) {
            if (_channel.read(buf) < 0) {
                throw new IOException("Connection closed while reading nonce (got " + buf.position() + " of " + _length + " bytes)");
            }
        }
        return buf.array();
    }

    private static void writeFully(SocketChannel _channel, byte[] _data) throws IOException {
        ByteBuffer buf = ByteBuffer.wrap(_data);
        while (buf.hasRemaining()) {
            _channel.write(buf);
        }
    }

    @Override
    protected void closeTransport() throws IOException {
        if (socket != null && socket.isOpen()) {
            socket.close();
        }

        if (serverSocket != null && serverSocket.isOpen()) {
            serverSocket.close();
        }
    }

}

