/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.github.hypfvieh.java-conventions")
}

description = "dbus-java-core"

java {
    withJavadocJar()
}
