/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.github.hypfvieh.java-conventions")
}

dependencies {
    api(project(":dbus-java-core"))
    api("com.github.jnr:jnr-unixsocket:0.38.20")
}

description = "dbus-java-transport-jnr-unixsocket"

java {
    withJavadocJar()
}
